version: "3.9"
services:
  db:
    image: postgres
  backend:
    restart: always
    container_name: backend
    command : python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - ./backend/server/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    restart: always
    command : npm start
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    stdin_open: true
