# Generated by Django 3.2.7 on 2021-11-16 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('event_code', models.CharField(blank=True, max_length=50)),
                ('file', models.CharField(blank=True, max_length=50)),
                ('event_date', models.DateField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_start', models.DateField()),
                ('calendar_end', models.DateField()),
                ('method', models.CharField(default='Kontantametoden', max_length=50)),
                ('account_plan', models.CharField(default='Bas', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.company')),
            ],
        ),
        migrations.CreateModel(
            name='EventRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('row_info', models.CharField(blank=True, max_length=150)),
                ('debit', models.IntegerField()),
                ('kredit', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeep.companycalendar')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeep.businessevent')),
            ],
        ),
        migrations.AddField(
            model_name='businessevent',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookkeep.companycalendar'),
        ),
        migrations.AddField(
            model_name='businessevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.company'),
        ),
    ]
